### ISSUE TITLE
describe_json can not handle json strings spanning multiple lines. It should!

### ISSUE THREAD

**Issue by vladiibine** [vladiibine/describe-json#1]
* Describe JSON version: 0.1.4
* Python version: *
* Operating System: *

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

While this works:
```
$ describe_json <<< '{"a":"B"}'                         
{"a": "B"}
```
...this does not
``` 
$ describe_json <<ASDF                                 
heredoc> {
heredoc>  "a": "B"
heredoc> }
heredoc> ASDF
Traceback (most recent call last):
  File "/home/vardelean/ve/tmp3/bin/describe_json", line 11, in <module>
    sys.exit(main())
  File "/home/vardelean/ve/tmp3/lib/python3.6/site-packages/describe_json/__init__.py", line 210, in main
    json_describer.get_struct(json.loads(line))))
  File "/home/vardelean/.pyenv/versions/3.6.3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/vardelean/.pyenv/versions/3.6.3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vardelean/.pyenv/versions/3.6.3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

...because `describe_json` assumes the json strings will be presented completely on 1 line

**Comment by vladiibine** [comment]
Also, since `jq` can do it, so should `describe_json`:

```
$ jq . <<ASDF
heredoc> {
heredoc>  "a": "B"
heredoc> }
heredoc> ASDF
{
  "a": "B"
}
```
